[package]
name = "bad-apple-rs"
version = "1.4.0"
authors = ["Lomirus <lomirus@qq.com>"]
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ctrlc = "3.4.5"

[profile.release]
lto = true
opt-level = "z"
strip = true
